added error message for missing sandboxes

diff --git a/sandboxd b/sandboxd
--- a/sandboxd
+++ b/sandboxd
@@ -22,9 +22,14 @@ function sandbox_delete_hooks(){
 # prepares environment and removes hooks
 function sandbox(){
   local cmd=$1
-  (>&2 echo "sandboxing $cmd ...")
-  sandbox_delete_hooks $cmd 
-  sandbox_init_$cmd # run user-defined sandbox 
+   if [[ "$(type $cmd | grep -o function)" = "function" ]]; then
+    (>&2 echo "sandboxing $cmd ...")
+    sandbox_delete_hooks $cmd 
+    sandbox_init_$cmd # run user-defined sandbox 
+  else
+    (>&2 echo "sandbox '$cmd' not found.\nHave you defined sandbox_init_$cmd(){ ... } in your ~/.sandboxrc?")
+    return 1
+  fi
 }
 
 function sandbox_hook(){
